### ISSUE TITLE
Recreate site's existing "Volunteer" page to Github Pages

### ISSUE THREAD

**Issue by Shaunm44** [CivicTechAtlanta/civictechatlanta.org#7]
Duplicate the Project Proposal page with Jekyll on Github Pages
https://www.codeforatlanta.org/volunteer

**Comment by Shaunm44** [comment]
~Hey @csun05 - any updates on this ticket?~

~No pressure. Just want to make sure any work you've done is able to be included in the final pull request.~

Ignore - this was handled under #14

**Comment by csun05** [comment]
Okay. I unassigned myself
